# Generated by Django 6.0.1 on 2026-02-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='tag',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('finished', 'Finished')], default='not_started', max_length=20),
        ),
    ]
